export const querykey = {
  user: "user",
  users: "users",
  client: "client",
  clients: "clients",
  key: "key",
  keys: "keys",
  key_codes: "key_codes",
  key_histories: "key_histories",
  batch: "batch",
  batchs: "batchs",
  key_type: "key_type",
  key_types: "key_types",
  dashboard: "dashboard",
};
