export const querykey = {
  user: "user",
  users: "users",
  client: "client",
  clients: "clients",
  key: "key",
  keys: "keys",
  key_connections: "key_connections",
  key_codes: "key_codes",
  key_histories: "key_histories",
  key_login: "key_login",
  key_logins: "key_logins",
  batch: "batch",
  batchs: "batchs",
  key_type: "key_type",
  key_types: "key_types",
  dashboard: "dashboard",
  computer_info: "computer_info",
  computers_info: "computers_info",
  computer_connections: "computer_connections",
};
