/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedKeysIndexRouteImport } from './routes/_protected/keys/index'
import { Route as ProtectedClientsIndexRouteImport } from './routes/_protected/clients/index'
import { Route as ProtectedBatchsIndexRouteImport } from './routes/_protected/batchs/index'
import { Route as ProtectedUsersUserIdRouteImport } from './routes/_protected/users/$userId'
import { Route as ProtectedKeysKeysRouteImport } from './routes/_protected/keys/$keys'
import { Route as ProtectedClientsClientIdRouteImport } from './routes/_protected/clients/$clientId'
import { Route as ProtectedBatchsBatchIdRouteImport } from './routes/_protected/batchs/$batchId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKeysIndexRoute = ProtectedKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClientsIndexRoute = ProtectedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBatchsIndexRoute = ProtectedBatchsIndexRouteImport.update({
  id: '/batchs/',
  path: '/batchs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersUserIdRoute = ProtectedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKeysKeysRoute = ProtectedKeysKeysRouteImport.update({
  id: '/keys/$keys',
  path: '/keys/$keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClientsClientIdRoute =
  ProtectedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBatchsBatchIdRoute = ProtectedBatchsBatchIdRouteImport.update({
  id: '/batchs/$batchId',
  path: '/batchs/$batchId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/reports': typeof ProtectedReportsRoute
  '/batchs/$batchId': typeof ProtectedBatchsBatchIdRoute
  '/clients/$clientId': typeof ProtectedClientsClientIdRoute
  '/keys/$keys': typeof ProtectedKeysKeysRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/batchs': typeof ProtectedBatchsIndexRoute
  '/clients': typeof ProtectedClientsIndexRoute
  '/keys': typeof ProtectedKeysIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/reports': typeof ProtectedReportsRoute
  '/batchs/$batchId': typeof ProtectedBatchsBatchIdRoute
  '/clients/$clientId': typeof ProtectedClientsClientIdRoute
  '/keys/$keys': typeof ProtectedKeysKeysRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/batchs': typeof ProtectedBatchsIndexRoute
  '/clients': typeof ProtectedClientsIndexRoute
  '/keys': typeof ProtectedKeysIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/batchs/$batchId': typeof ProtectedBatchsBatchIdRoute
  '/_protected/clients/$clientId': typeof ProtectedClientsClientIdRoute
  '/_protected/keys/$keys': typeof ProtectedKeysKeysRoute
  '/_protected/users/$userId': typeof ProtectedUsersUserIdRoute
  '/_protected/batchs/': typeof ProtectedBatchsIndexRoute
  '/_protected/clients/': typeof ProtectedClientsIndexRoute
  '/_protected/keys/': typeof ProtectedKeysIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/batchs/$batchId'
    | '/clients/$clientId'
    | '/keys/$keys'
    | '/users/$userId'
    | '/batchs'
    | '/clients'
    | '/keys'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/batchs/$batchId'
    | '/clients/$clientId'
    | '/keys/$keys'
    | '/users/$userId'
    | '/batchs'
    | '/clients'
    | '/keys'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/reports'
    | '/_protected/batchs/$batchId'
    | '/_protected/clients/$clientId'
    | '/_protected/keys/$keys'
    | '/_protected/users/$userId'
    | '/_protected/batchs/'
    | '/_protected/clients/'
    | '/_protected/keys/'
    | '/_protected/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/keys/': {
      id: '/_protected/keys/'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof ProtectedKeysIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clients/': {
      id: '/_protected/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ProtectedClientsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/batchs/': {
      id: '/_protected/batchs/'
      path: '/batchs'
      fullPath: '/batchs'
      preLoaderRoute: typeof ProtectedBatchsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/$userId': {
      id: '/_protected/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ProtectedUsersUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/keys/$keys': {
      id: '/_protected/keys/$keys'
      path: '/keys/$keys'
      fullPath: '/keys/$keys'
      preLoaderRoute: typeof ProtectedKeysKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clients/$clientId': {
      id: '/_protected/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ProtectedClientsClientIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/batchs/$batchId': {
      id: '/_protected/batchs/$batchId'
      path: '/batchs/$batchId'
      fullPath: '/batchs/$batchId'
      preLoaderRoute: typeof ProtectedBatchsBatchIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedBatchsBatchIdRoute: typeof ProtectedBatchsBatchIdRoute
  ProtectedClientsClientIdRoute: typeof ProtectedClientsClientIdRoute
  ProtectedKeysKeysRoute: typeof ProtectedKeysKeysRoute
  ProtectedUsersUserIdRoute: typeof ProtectedUsersUserIdRoute
  ProtectedBatchsIndexRoute: typeof ProtectedBatchsIndexRoute
  ProtectedClientsIndexRoute: typeof ProtectedClientsIndexRoute
  ProtectedKeysIndexRoute: typeof ProtectedKeysIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedBatchsBatchIdRoute: ProtectedBatchsBatchIdRoute,
  ProtectedClientsClientIdRoute: ProtectedClientsClientIdRoute,
  ProtectedKeysKeysRoute: ProtectedKeysKeysRoute,
  ProtectedUsersUserIdRoute: ProtectedUsersUserIdRoute,
  ProtectedBatchsIndexRoute: ProtectedBatchsIndexRoute,
  ProtectedClientsIndexRoute: ProtectedClientsIndexRoute,
  ProtectedKeysIndexRoute: ProtectedKeysIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
